edition = "2024";
package main;
option go_package = "github.com/zosmac/gomon";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

service Gomon {
  rpc GetMessages(MessageTypes) returns (stream Message) {}
}

message MessageTypes {
	int32 Types = 1;
}

message FileObservation {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  uint64 FileEventID = 7;
  string Message = 8;
}

message FilesystemMeasurement {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Mount = 6;
  string Path = 7;
  string Type = 8;
  int64 Total = 9;
  int64 Used = 10;
  int64 Free = 11;
  int64 Available = 12;
  int64 Files = 13;
  int64 FreeFiles = 14;
}

message IoMeasurement {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Device = 6;
  string Major = 7;
  string Minor = 8;
  int64 TotalSize = 9;
  int64 BlockSize = 10;
  int64 ReadOperations = 11;
  int64 Read = 12;
  google.protobuf.Duration ReadTime = 13;
  int64 WriteOperations = 14;
  int64 Write = 15;
  google.protobuf.Duration WriteTime = 16;
}

message LogsObservation {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  int64 Pid = 7;
  string Sender = 8;
  string Message = 9;
}

message NetworkMeasurement {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  int64 Index = 7;
  string Flags = 8;
  int64 Mtu = 9;
  string Mac = 10;
  string Address = 11;
  string Netmask = 12;
  string Broadcast = 13;
  string Linklocal6 = 14;
  string Address6 = 15;
  int64 Receive = 16;
  int64 ReceivePackets = 17;
  int64 ReceiveErrors = 18;
  int64 ReceiveDropped = 19;
  int64 ReceiveMulticast = 20;
  int64 Transmit = 21;
  int64 TransmitPackets = 22;
  int64 TransmitErrors = 23;
  int64 TransmitDropped = 24;
  int64 TransmitCollisions = 25;
  int64 TransmitMulticast = 26;
}

message ProcessObservation {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  int64 Pid = 7;
  google.protobuf.Timestamp Starttime = 8;
  string Message = 9;
}

message ProcessMeasurement {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  int64 Pid = 7;
  google.protobuf.Timestamp Starttime = 8;
  int64 Ppid = 9;
  int64 Pgid = 10;
  string Tty = 11;
  int64 UID = 12;
  int64 GID = 13;
  string Username = 14;
  string Groupname = 15;
  string Executable = 16;
  repeated string Args = 17;
  repeated string Envs = 18;
  string Cwd = 19;
  string Root = 20;
  repeated Connection Connections = 21;
  message Connection {
    string Type = 1;
    Endpoint Self = 2;
    message Endpoint {
      string Name = 1;
      int64 Pid = 2;
    }
    Endpoint Peer = 3;
    message Endpoint {
      string Name = 1;
      int64 Pid = 2;
    }
  }
  string Status = 22;
  int64 Nice = 23;
  int64 Priority = 24;
  int64 Threads = 25;
  google.protobuf.Duration User = 26;
  google.protobuf.Duration System = 27;
  google.protobuf.Duration Total = 28;
  int64 Size = 29;
  int64 Resident = 30;
  int64 PageFaults = 31;
  int64 ContextSwitches = 32;
  int64 ReadActual = 33;
  int64 WriteActual = 34;
  int64 WriteRequested = 35;
}

message ServeMeasurement {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  string Address = 7;
  repeated string Endpoints = 8;
  int64 HTTPRequests = 9;
  int64 Collections = 10;
  google.protobuf.Duration CollectionTime = 11;
  int64 LokiStreams = 12;
}

message SystemMeasurement {
  google.protobuf.Timestamp Timestamp = 1;
  string Host = 2;
  string Platform = 3;
  string Source = 4;
  string Event = 5;
  string Name = 6;
  google.protobuf.Timestamp Boottime = 7;
  google.protobuf.Duration Uptime = 8;
  int64 ProcessesMaximum = 9;
  int64 ProcessesPerUser = 10;
  int64 OpenFilesMaximum = 11;
  int64 OpenFilesPerProcess = 12;
  int64 OpenFilesCurrent = 13;
  LoadAverage LoadAverage = 14;
  message LoadAverage {
    double OneMinute = 1;
    double FiveMinute = 2;
    double FifteenMinute = 3;
  }
  CPU Cpu = 15;
  message CPU {
    google.protobuf.Duration Total = 1;
    google.protobuf.Duration User = 2;
    google.protobuf.Duration System = 3;
    google.protobuf.Duration Idle = 4;
  }
  int64 CpuCount = 16;
  repeated CPU Cpus = 17;
  message CPU {
    google.protobuf.Duration Total = 1;
    google.protobuf.Duration User = 2;
    google.protobuf.Duration System = 3;
    google.protobuf.Duration Idle = 4;
  }
  Memory Memory = 18;
  message Memory {
    int64 Total = 1;
    int64 Free = 2;
    int64 Used = 3;
    int64 FreeActual = 4;
    int64 UsedActual = 5;
  }
  Swap Swap = 19;
  message Swap {
    int64 Total = 1;
    int64 Free = 2;
    int64 Used = 3;
  }
  ProcStats ProcessStats = 20;
  message ProcStats {
    int64 Count = 1;
    int64 Active = 2;
    int64 Execed = 3;
    int64 Exited = 4;
    google.protobuf.Duration Cpu = 5;
  }
}

func CopyFileObservation(src *file.Observation) FileObservation {
  return FileObservation{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    FileEventID: src.FileEventID,
    Message: src.Message,
  }
}

func CopyFilesystemMeasurement(src *filesystem.Measurement) FilesystemMeasurement {
  return FilesystemMeasurement{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Mount: src.Mount,
    Path: src.Path,
    Type: src.Type,
    Total: src.Total,
    Used: src.Used,
    Free: src.Free,
    Available: src.Available,
    Files: src.Files,
    FreeFiles: src.FreeFiles,
  }
}

func CopyIoMeasurement(src *io.Measurement) IoMeasurement {
  return IoMeasurement{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Device: src.Device,
    Major: src.Major,
    Minor: src.Minor,
    TotalSize: src.TotalSize,
    BlockSize: src.BlockSize,
    ReadOperations: src.ReadOperations,
    Read: src.Read,
    ReadTime: src.ReadTime,
    WriteOperations: src.WriteOperations,
    Write: src.Write,
    WriteTime: src.WriteTime,
  }
}

func CopyLogsObservation(src *logs.Observation) LogsObservation {
  return LogsObservation{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    Pid: src.Pid,
    Sender: src.Sender,
    Message: src.Message,
  }
}

func CopyNetworkMeasurement(src *network.Measurement) NetworkMeasurement {
  return NetworkMeasurement{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    Index: src.Index,
    Flags: src.Flags,
    Mtu: src.Mtu,
    Mac: src.Mac,
    Address: src.Address,
    Netmask: src.Netmask,
    Broadcast: src.Broadcast,
    Linklocal6: src.Linklocal6,
    Address6: src.Address6,
    Receive: src.Receive,
    ReceivePackets: src.ReceivePackets,
    ReceiveErrors: src.ReceiveErrors,
    ReceiveDropped: src.ReceiveDropped,
    ReceiveMulticast: src.ReceiveMulticast,
    Transmit: src.Transmit,
    TransmitPackets: src.TransmitPackets,
    TransmitErrors: src.TransmitErrors,
    TransmitDropped: src.TransmitDropped,
    TransmitCollisions: src.TransmitCollisions,
    TransmitMulticast: src.TransmitMulticast,
  }
}

func CopyProcessObservation(src *process.Observation) ProcessObservation {
  return ProcessObservation{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    Pid: src.Pid,
    Starttime: src.Starttime,
    Message: src.Message,
  }
}

func CopyProcessMeasurement(src *process.Measurement) ProcessMeasurement {
  return ProcessMeasurement{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    Pid: src.Pid,
    Starttime: src.Starttime,
    Ppid: src.Ppid,
    Pgid: src.Pgid,
    Tty: src.Tty,
    UID: src.UID,
    GID: src.GID,
    Username: src.Username,
    Groupname: src.Groupname,
    Executable: src.Executable,
    Args: src.Args,
    Envs: src.Envs,
    Cwd: src.Cwd,
    Root: src.Root,
    Connections: src.Connections,
    Self: src.Self,
    Peer: src.Peer,
    Status: src.Status,
    Nice: src.Nice,
    Priority: src.Priority,
    Threads: src.Threads,
    User: src.User,
    System: src.System,
    Total: src.Total,
    Size: src.Size,
    Resident: src.Resident,
    PageFaults: src.PageFaults,
    ContextSwitches: src.ContextSwitches,
    ReadActual: src.ReadActual,
    WriteActual: src.WriteActual,
    WriteRequested: src.WriteRequested,
  }
}

func CopyServeMeasurement(src *serve.Measurement) ServeMeasurement {
  return ServeMeasurement{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    Address: src.Address,
    Endpoints: src.Endpoints,
    HTTPRequests: src.HTTPRequests,
    Collections: src.Collections,
    CollectionTime: src.CollectionTime,
    LokiStreams: src.LokiStreams,
  }
}

func CopySystemMeasurement(src *system.Measurement) SystemMeasurement {
  return SystemMeasurement{
    Timestamp: src.Timestamp,
    Host: src.Host,
    Platform: src.Platform,
    Source: src.Source,
    Event: src.Event,
    Name: src.Name,
    Boottime: src.Boottime,
    Uptime: src.Uptime,
    ProcessesMaximum: src.ProcessesMaximum,
    ProcessesPerUser: src.ProcessesPerUser,
    OpenFilesMaximum: src.OpenFilesMaximum,
    OpenFilesPerProcess: src.OpenFilesPerProcess,
    OpenFilesCurrent: src.OpenFilesCurrent,
    LoadAverage: src.LoadAverage,
    Cpu: src.Cpu,
    CpuCount: src.CpuCount,
    Cpus: src.Cpus,
    Memory: src.Memory,
    Swap: src.Swap,
    ProcessStats: src.ProcessStats,
  }
}

