{
 "title": "Gomon Dashboard",
 "description": "Display system measurements and observations captured by Gomon",
 "tags": [
  "gomon",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "(time()-gomon_system_uptime_seconds)*1000",
     "legendFormat": "Boottime (UTC):"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomon_system_uptime_seconds", "legendFormat": "Uptime:" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gomon_system_cpu_count", "legendFormat": "CPU Count:" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gomon_system_memory_total_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gomon_system_load_average_one_minute",
     "legendFormat": "load average 1"
    },
    {
     "expr": "gomon_system_load_average_five_minute",
     "legendFormat": "load average 5"
    },
    {
     "expr": "gomon_system_load_average_fifteen_minute",
     "legendFormat": "load average 15"
    }
   ]
  },
  {
   "title": "System Memory and Swap Used (log2)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gomon_system_memory_used_actual_bytes",
     "legendFormat": "memory used"
    },
    { "expr": "gomon_system_swap_total_bytes", "legendFormat": "swap total" },
    { "expr": "gomon_system_swap_used_bytes", "legendFormat": "swap used" }
   ]
  },
  {
   "title": "Network and Device I/O (log2)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(gomon_io_read_bytes[1m])/1024/60",
     "legendFormat": "I/O read"
    },
    {
     "expr": "rate(gomon_io_write_bytes[1m])/1024/60",
     "legendFormat": "I/O write"
    },
    {
     "expr": "rate(gomon_network_receive_bytes{id='en0'}[1m])/60",
     "legendFormat": "receive {{id}}"
    },
    {
     "expr": "rate(gomon_network_transmit_bytes{id='en0'}[1m])/60",
     "legendFormat": "transmit {{id}}"
    },
    {
     "expr": "rate(gomon_system_interface_measure_receive_bytes{id='lo0'}[1m])/60",
     "legendFormat": "receive {{id}}"
    },
    {
     "expr": "rate(gomon_system_interface_measure_transmit_bytes{id='lo0'}[1m])/60",
     "legendFormat": "transmit {{id}}"
    }
   ]
  },
  {
   "title": "System and Top5 Process CPU Usage (log2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(gomon_system_cpu_total_seconds[1m])",
     "legendFormat": "system"
    },
    {
     "expr": "topk(5, (rate(gomon_process_total_seconds[1m])))",
     "legendFormat": "process {{id}}"
    }
   ]
  },
  {
   "title": "Top5 Process Res. and Virt. Memory Usage (log2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk(5, gomon_process_size_bytes/1024/1024)",
     "legendFormat": "virtual {{id}}"
    },
    {
     "expr": "topk(5, gomon_process_resident_bytes/1024/1024)",
     "legendFormat": "resident {{id}}"
    }
   ]
  },
  {
   "title": "System and Top5 Process I/O (log2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(5, (rate(gomon_io_read_bytes[1m])+rate(gomon_io_write_bytes[1m])))/1024/60",
     "legendFormat": "system"
    },
    {
     "expr": "topk(5, (rate(gomon_process_read_actual_bytes[1m])+rate(gomon_process_write_actual_bytes[1m])))/1024/60",
     "legendFormat": "process {{id}}"
    }
   ]
  },
  {
   "title": "File, Log, and Process Event Stream",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{source=~\"(file|log|oslog|syslog|process)\"}"
    }
   ]
  }
 ]
}