// Copyright © 2021 The Gomon Project.

// Code generated by go generate. DO NOT EDIT.

package core

var (
	// vmmp is "Version, Major, Minor, Patch"
	// vmmp = "v3.0.0-9924576c6c20"

	// Dependencies import paths and versions
	// github.com/StackExchange/wmi v1.2.1
	// github.com/beorn7/perks v1.0.1
	// github.com/cespare/xxhash/v2 v2.2.0
	// github.com/davecgh/go-spew v1.1.1
	// github.com/go-ole/go-ole v1.2.6
	// github.com/golang/protobuf v1.5.2
	// github.com/google/go-cmp v0.5.9
	// github.com/kr/pretty v0.3.1
	// github.com/kr/text v0.2.0
	// github.com/matttproud/golang_protobuf_extensions v1.0.4
	// github.com/prometheus/client_golang v1.14.0
	// github.com/prometheus/client_model v0.3.0
	// github.com/prometheus/common v0.39.0
	// github.com/prometheus/procfs v0.9.0
	// github.com/rogpeppe/go-internal v1.9.0
	// golang.org/x/net v0.5.0
	// golang.org/x/sys v0.4.0
	// google.golang.org/protobuf v1.28.1
	// gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
	// gopkg.in/yaml.v2 v2.4.0
)
