{
 "title": "Gomon Dashboard",
 "description": "Display system measurements and observations captured by Gomon",
 "tags": [
  "gomon",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "System",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "(time()-gomon_system_uptime_seconds)*1000",
     "legendFormat": "Boottime (UTC)"
    },
    { "expr": "gomon_system_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gomon_system_memory_total_bytes",
     "legendFormat": "Total"
    },
    {
     "expr": "gomon_system_memory_used_actual_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "gomon_system_memory_used_actual_bytes/gomon_system_memory_total_bytes",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomon_system_cpu_count", "legendFormat": "Count" },
    {
     "expr": "(rate(gomon_system_cpu_system_seconds[$__rate_interval])+rate(gomon_system_cpu_user_seconds[$__rate_interval]))/rate(gomon_system_cpu_total_seconds[$__rate_interval])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gomon_system_load_average_one_minute",
     "legendFormat": "load average 1"
    },
    {
     "expr": "gomon_system_load_average_five_minute",
     "legendFormat": "load average 5"
    },
    {
     "expr": "gomon_system_load_average_fifteen_minute",
     "legendFormat": "load average 15"
    }
   ]
  },
  {
   "title": "Prometheus and Loki Collections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(gomon_serve_collections[$__rate_interval])",
     "legendFormat": "{{id}} collections"
    },
    {
     "expr": "rate(gomon_serve_collection_time_seconds[$__rate_interval])",
     "legendFormat": "{{id}} collection time"
    },
    {
     "expr": "rate(gomon_serve_loki_streams[$__rate_interval])",
     "legendFormat": "loki streams"
    }
   ]
  },
  {
   "title": "Network and Device I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gomon_io_read_bytes[$__rate_interval])",
     "legendFormat": "I/O read {{id}}"
    },
    {
     "expr": "-rate(gomon_io_write_bytes[$__rate_interval])",
     "legendFormat": "I/O write {{id}}"
    },
    {
     "expr": "rate(gomon_network_receive_bytes{id='en0'}[$__rate_interval])",
     "legendFormat": "receive {{id}}"
    },
    {
     "expr": "-rate(gomon_network_transmit_bytes{id='en0'}[$__rate_interval])",
     "legendFormat": "transmit {{id}}"
    },
    {
     "expr": "rate(gomon_network_receive_bytes{id='lo0'}[$__rate_interval])",
     "legendFormat": "receive {{id}}"
    },
    {
     "expr": "-rate(gomon_network_transmit_bytes{id='lo0'}[$__rate_interval])",
     "legendFormat": "transmit {{id}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(2, rate(gomon_process_total_seconds[$__rate_interval]))",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "System and Process I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gomon_io_read_bytes[$__rate_interval])",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "-rate(gomon_io_write_bytes[$__rate_interval])",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "topk(2, rate(gomon_process_read_actual_bytes[$__rate_interval]))",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "-topk(2, rate(gomon_process_write_actual_bytes[$__rate_interval]))",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, gomon_process_resident_bytes)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "File, Log, and Process Event Stream",
   "type": "logs",
   "gridPos": { "h": 21, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=~\"(file|logs|process)\"}"
    }
   ]
  }
 ]
}