// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gomon.proto

package gomon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event         string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	FileEventId   uint64                 `protobuf:"varint,7,opt,name=file_event_id,json=fileEventId,proto3" json:"file_event_id,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileObservation) Reset() {
	*x = FileObservation{}
	mi := &file_gomon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileObservation) ProtoMessage() {}

func (x *FileObservation) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileObservation.ProtoReflect.Descriptor instead.
func (*FileObservation) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{0}
}

func (x *FileObservation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FileObservation) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FileObservation) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *FileObservation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileObservation) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *FileObservation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileObservation) GetFileEventId() uint64 {
	if x != nil {
		return x.FileEventId
	}
	return 0
}

func (x *FileObservation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FilesystemMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event         string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Mount         string                 `protobuf:"bytes,6,opt,name=mount,proto3" json:"mount,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Total         int64                  `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	Used          int64                  `protobuf:"varint,10,opt,name=used,proto3" json:"used,omitempty"`
	Free          int64                  `protobuf:"varint,11,opt,name=free,proto3" json:"free,omitempty"`
	Available     int64                  `protobuf:"varint,12,opt,name=available,proto3" json:"available,omitempty"`
	Files         int64                  `protobuf:"varint,13,opt,name=files,proto3" json:"files,omitempty"`
	FreeFiles     int64                  `protobuf:"varint,14,opt,name=free_files,json=freeFiles,proto3" json:"free_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemMeasurement) Reset() {
	*x = FilesystemMeasurement{}
	mi := &file_gomon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemMeasurement) ProtoMessage() {}

func (x *FilesystemMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemMeasurement.ProtoReflect.Descriptor instead.
func (*FilesystemMeasurement) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{1}
}

func (x *FilesystemMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FilesystemMeasurement) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FilesystemMeasurement) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *FilesystemMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FilesystemMeasurement) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *FilesystemMeasurement) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *FilesystemMeasurement) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilesystemMeasurement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FilesystemMeasurement) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FilesystemMeasurement) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *FilesystemMeasurement) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *FilesystemMeasurement) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *FilesystemMeasurement) GetFiles() int64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *FilesystemMeasurement) GetFreeFiles() int64 {
	if x != nil {
		return x.FreeFiles
	}
	return 0
}

type IoMeasurement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host            string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform        string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source          string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event           string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Device          string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Major           string                 `protobuf:"bytes,7,opt,name=major,proto3" json:"major,omitempty"`
	Minor           string                 `protobuf:"bytes,8,opt,name=minor,proto3" json:"minor,omitempty"`
	TotalSize       int64                  `protobuf:"varint,9,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	BlockSize       int64                  `protobuf:"varint,10,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	ReadOperations  int64                  `protobuf:"varint,11,opt,name=read_operations,json=readOperations,proto3" json:"read_operations,omitempty"`
	Read            int64                  `protobuf:"varint,12,opt,name=read,proto3" json:"read,omitempty"`
	ReadTime        *durationpb.Duration   `protobuf:"bytes,13,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	WriteOperations int64                  `protobuf:"varint,14,opt,name=write_operations,json=writeOperations,proto3" json:"write_operations,omitempty"`
	Write           int64                  `protobuf:"varint,15,opt,name=write,proto3" json:"write,omitempty"`
	WriteTime       *durationpb.Duration   `protobuf:"bytes,16,opt,name=write_time,json=writeTime,proto3" json:"write_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IoMeasurement) Reset() {
	*x = IoMeasurement{}
	mi := &file_gomon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoMeasurement) ProtoMessage() {}

func (x *IoMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoMeasurement.ProtoReflect.Descriptor instead.
func (*IoMeasurement) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{2}
}

func (x *IoMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IoMeasurement) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *IoMeasurement) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *IoMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IoMeasurement) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *IoMeasurement) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *IoMeasurement) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *IoMeasurement) GetMinor() string {
	if x != nil {
		return x.Minor
	}
	return ""
}

func (x *IoMeasurement) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *IoMeasurement) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *IoMeasurement) GetReadOperations() int64 {
	if x != nil {
		return x.ReadOperations
	}
	return 0
}

func (x *IoMeasurement) GetRead() int64 {
	if x != nil {
		return x.Read
	}
	return 0
}

func (x *IoMeasurement) GetReadTime() *durationpb.Duration {
	if x != nil {
		return x.ReadTime
	}
	return nil
}

func (x *IoMeasurement) GetWriteOperations() int64 {
	if x != nil {
		return x.WriteOperations
	}
	return 0
}

func (x *IoMeasurement) GetWrite() int64 {
	if x != nil {
		return x.Write
	}
	return 0
}

func (x *IoMeasurement) GetWriteTime() *durationpb.Duration {
	if x != nil {
		return x.WriteTime
	}
	return nil
}

type LogsObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event         string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Pid           int64                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Sender        string                 `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsObservation) Reset() {
	*x = LogsObservation{}
	mi := &file_gomon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsObservation) ProtoMessage() {}

func (x *LogsObservation) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsObservation.ProtoReflect.Descriptor instead.
func (*LogsObservation) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{3}
}

func (x *LogsObservation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogsObservation) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LogsObservation) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LogsObservation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogsObservation) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *LogsObservation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogsObservation) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LogsObservation) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *LogsObservation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NetworkMeasurement struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host               string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform           string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source             string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event              string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name               string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Index              int64                  `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	Flags              string                 `protobuf:"bytes,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Mtu                int64                  `protobuf:"varint,9,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Mac                string                 `protobuf:"bytes,10,opt,name=mac,proto3" json:"mac,omitempty"`
	Address            string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	Netmask            string                 `protobuf:"bytes,12,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Broadcast          string                 `protobuf:"bytes,13,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Linklocal6         string                 `protobuf:"bytes,14,opt,name=linklocal6,proto3" json:"linklocal6,omitempty"`
	Address6           string                 `protobuf:"bytes,15,opt,name=address6,proto3" json:"address6,omitempty"`
	Receive            int64                  `protobuf:"varint,16,opt,name=receive,proto3" json:"receive,omitempty"`
	ReceivePackets     int64                  `protobuf:"varint,17,opt,name=receive_packets,json=receivePackets,proto3" json:"receive_packets,omitempty"`
	ReceiveErrors      int64                  `protobuf:"varint,18,opt,name=receive_errors,json=receiveErrors,proto3" json:"receive_errors,omitempty"`
	ReceiveDropped     int64                  `protobuf:"varint,19,opt,name=receive_dropped,json=receiveDropped,proto3" json:"receive_dropped,omitempty"`
	ReceiveMulticast   int64                  `protobuf:"varint,20,opt,name=receive_multicast,json=receiveMulticast,proto3" json:"receive_multicast,omitempty"`
	Transmit           int64                  `protobuf:"varint,21,opt,name=transmit,proto3" json:"transmit,omitempty"`
	TransmitPackets    int64                  `protobuf:"varint,22,opt,name=transmit_packets,json=transmitPackets,proto3" json:"transmit_packets,omitempty"`
	TransmitErrors     int64                  `protobuf:"varint,23,opt,name=transmit_errors,json=transmitErrors,proto3" json:"transmit_errors,omitempty"`
	TransmitDropped    int64                  `protobuf:"varint,24,opt,name=transmit_dropped,json=transmitDropped,proto3" json:"transmit_dropped,omitempty"`
	TransmitCollisions int64                  `protobuf:"varint,25,opt,name=transmit_collisions,json=transmitCollisions,proto3" json:"transmit_collisions,omitempty"`
	TransmitMulticast  int64                  `protobuf:"varint,26,opt,name=transmit_multicast,json=transmitMulticast,proto3" json:"transmit_multicast,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkMeasurement) Reset() {
	*x = NetworkMeasurement{}
	mi := &file_gomon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMeasurement) ProtoMessage() {}

func (x *NetworkMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMeasurement.ProtoReflect.Descriptor instead.
func (*NetworkMeasurement) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NetworkMeasurement) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkMeasurement) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *NetworkMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NetworkMeasurement) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NetworkMeasurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkMeasurement) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NetworkMeasurement) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *NetworkMeasurement) GetMtu() int64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkMeasurement) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkMeasurement) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NetworkMeasurement) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

func (x *NetworkMeasurement) GetBroadcast() string {
	if x != nil {
		return x.Broadcast
	}
	return ""
}

func (x *NetworkMeasurement) GetLinklocal6() string {
	if x != nil {
		return x.Linklocal6
	}
	return ""
}

func (x *NetworkMeasurement) GetAddress6() string {
	if x != nil {
		return x.Address6
	}
	return ""
}

func (x *NetworkMeasurement) GetReceive() int64 {
	if x != nil {
		return x.Receive
	}
	return 0
}

func (x *NetworkMeasurement) GetReceivePackets() int64 {
	if x != nil {
		return x.ReceivePackets
	}
	return 0
}

func (x *NetworkMeasurement) GetReceiveErrors() int64 {
	if x != nil {
		return x.ReceiveErrors
	}
	return 0
}

func (x *NetworkMeasurement) GetReceiveDropped() int64 {
	if x != nil {
		return x.ReceiveDropped
	}
	return 0
}

func (x *NetworkMeasurement) GetReceiveMulticast() int64 {
	if x != nil {
		return x.ReceiveMulticast
	}
	return 0
}

func (x *NetworkMeasurement) GetTransmit() int64 {
	if x != nil {
		return x.Transmit
	}
	return 0
}

func (x *NetworkMeasurement) GetTransmitPackets() int64 {
	if x != nil {
		return x.TransmitPackets
	}
	return 0
}

func (x *NetworkMeasurement) GetTransmitErrors() int64 {
	if x != nil {
		return x.TransmitErrors
	}
	return 0
}

func (x *NetworkMeasurement) GetTransmitDropped() int64 {
	if x != nil {
		return x.TransmitDropped
	}
	return 0
}

func (x *NetworkMeasurement) GetTransmitCollisions() int64 {
	if x != nil {
		return x.TransmitCollisions
	}
	return 0
}

func (x *NetworkMeasurement) GetTransmitMulticast() int64 {
	if x != nil {
		return x.TransmitMulticast
	}
	return 0
}

type ProcessObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event         string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Pid           int64                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Starttime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessObservation) Reset() {
	*x = ProcessObservation{}
	mi := &file_gomon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessObservation) ProtoMessage() {}

func (x *ProcessObservation) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessObservation.ProtoReflect.Descriptor instead.
func (*ProcessObservation) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessObservation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ProcessObservation) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProcessObservation) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ProcessObservation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProcessObservation) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ProcessObservation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessObservation) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessObservation) GetStarttime() *timestamppb.Timestamp {
	if x != nil {
		return x.Starttime
	}
	return nil
}

func (x *ProcessObservation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessMeasurement struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp            `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host            string                            `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform        string                            `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source          string                            `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event           string                            `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name            string                            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Pid             int64                             `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Starttime       *timestamppb.Timestamp            `protobuf:"bytes,8,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Ppid            int64                             `protobuf:"varint,9,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Pgid            int64                             `protobuf:"varint,10,opt,name=pgid,proto3" json:"pgid,omitempty"`
	Tty             string                            `protobuf:"bytes,11,opt,name=tty,proto3" json:"tty,omitempty"`
	Uid             int64                             `protobuf:"varint,12,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid             int64                             `protobuf:"varint,13,opt,name=gid,proto3" json:"gid,omitempty"`
	Username        string                            `protobuf:"bytes,14,opt,name=username,proto3" json:"username,omitempty"`
	Groupname       string                            `protobuf:"bytes,15,opt,name=groupname,proto3" json:"groupname,omitempty"`
	Executable      string                            `protobuf:"bytes,16,opt,name=executable,proto3" json:"executable,omitempty"`
	Args            []string                          `protobuf:"bytes,17,rep,name=args,proto3" json:"args,omitempty"`
	Envs            []string                          `protobuf:"bytes,18,rep,name=envs,proto3" json:"envs,omitempty"`
	Cwd             string                            `protobuf:"bytes,19,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Root            string                            `protobuf:"bytes,20,opt,name=root,proto3" json:"root,omitempty"`
	Connections     []*ProcessMeasurement_Connections `protobuf:"bytes,21,rep,name=connections,proto3" json:"connections,omitempty"`
	Status          string                            `protobuf:"bytes,22,opt,name=status,proto3" json:"status,omitempty"`
	Nice            int64                             `protobuf:"varint,23,opt,name=nice,proto3" json:"nice,omitempty"`
	Priority        int64                             `protobuf:"varint,24,opt,name=priority,proto3" json:"priority,omitempty"`
	Threads         int64                             `protobuf:"varint,25,opt,name=threads,proto3" json:"threads,omitempty"`
	User            *durationpb.Duration              `protobuf:"bytes,26,opt,name=user,proto3" json:"user,omitempty"`
	System          *durationpb.Duration              `protobuf:"bytes,27,opt,name=system,proto3" json:"system,omitempty"`
	Total           *durationpb.Duration              `protobuf:"bytes,28,opt,name=total,proto3" json:"total,omitempty"`
	Size            int64                             `protobuf:"varint,29,opt,name=size,proto3" json:"size,omitempty"`
	Resident        int64                             `protobuf:"varint,30,opt,name=resident,proto3" json:"resident,omitempty"`
	PageFaults      int64                             `protobuf:"varint,31,opt,name=page_faults,json=pageFaults,proto3" json:"page_faults,omitempty"`
	ContextSwitches int64                             `protobuf:"varint,32,opt,name=context_switches,json=contextSwitches,proto3" json:"context_switches,omitempty"`
	ReadActual      int64                             `protobuf:"varint,33,opt,name=read_actual,json=readActual,proto3" json:"read_actual,omitempty"`
	WriteActual     int64                             `protobuf:"varint,34,opt,name=write_actual,json=writeActual,proto3" json:"write_actual,omitempty"`
	WriteRequested  int64                             `protobuf:"varint,35,opt,name=write_requested,json=writeRequested,proto3" json:"write_requested,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessMeasurement) Reset() {
	*x = ProcessMeasurement{}
	mi := &file_gomon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMeasurement) ProtoMessage() {}

func (x *ProcessMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMeasurement.ProtoReflect.Descriptor instead.
func (*ProcessMeasurement) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ProcessMeasurement) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProcessMeasurement) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ProcessMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProcessMeasurement) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ProcessMeasurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMeasurement) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMeasurement) GetStarttime() *timestamppb.Timestamp {
	if x != nil {
		return x.Starttime
	}
	return nil
}

func (x *ProcessMeasurement) GetPpid() int64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessMeasurement) GetPgid() int64 {
	if x != nil {
		return x.Pgid
	}
	return 0
}

func (x *ProcessMeasurement) GetTty() string {
	if x != nil {
		return x.Tty
	}
	return ""
}

func (x *ProcessMeasurement) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessMeasurement) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProcessMeasurement) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProcessMeasurement) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *ProcessMeasurement) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *ProcessMeasurement) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessMeasurement) GetEnvs() []string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ProcessMeasurement) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ProcessMeasurement) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ProcessMeasurement) GetConnections() []*ProcessMeasurement_Connections {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *ProcessMeasurement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessMeasurement) GetNice() int64 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *ProcessMeasurement) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProcessMeasurement) GetThreads() int64 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ProcessMeasurement) GetUser() *durationpb.Duration {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ProcessMeasurement) GetSystem() *durationpb.Duration {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ProcessMeasurement) GetTotal() *durationpb.Duration {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *ProcessMeasurement) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProcessMeasurement) GetResident() int64 {
	if x != nil {
		return x.Resident
	}
	return 0
}

func (x *ProcessMeasurement) GetPageFaults() int64 {
	if x != nil {
		return x.PageFaults
	}
	return 0
}

func (x *ProcessMeasurement) GetContextSwitches() int64 {
	if x != nil {
		return x.ContextSwitches
	}
	return 0
}

func (x *ProcessMeasurement) GetReadActual() int64 {
	if x != nil {
		return x.ReadActual
	}
	return 0
}

func (x *ProcessMeasurement) GetWriteActual() int64 {
	if x != nil {
		return x.WriteActual
	}
	return 0
}

func (x *ProcessMeasurement) GetWriteRequested() int64 {
	if x != nil {
		return x.WriteRequested
	}
	return 0
}

type ServeMeasurement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host           string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform       string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event          string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Address        string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Endpoints      []string               `protobuf:"bytes,8,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	HttpRequests   int64                  `protobuf:"varint,9,opt,name=http_requests,json=httpRequests,proto3" json:"http_requests,omitempty"`
	Collections    int64                  `protobuf:"varint,10,opt,name=collections,proto3" json:"collections,omitempty"`
	CollectionTime *durationpb.Duration   `protobuf:"bytes,11,opt,name=collection_time,json=collectionTime,proto3" json:"collection_time,omitempty"`
	LokiStreams    int64                  `protobuf:"varint,12,opt,name=loki_streams,json=lokiStreams,proto3" json:"loki_streams,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServeMeasurement) Reset() {
	*x = ServeMeasurement{}
	mi := &file_gomon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeMeasurement) ProtoMessage() {}

func (x *ServeMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeMeasurement.ProtoReflect.Descriptor instead.
func (*ServeMeasurement) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{7}
}

func (x *ServeMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServeMeasurement) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServeMeasurement) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ServeMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ServeMeasurement) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ServeMeasurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServeMeasurement) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServeMeasurement) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ServeMeasurement) GetHttpRequests() int64 {
	if x != nil {
		return x.HttpRequests
	}
	return 0
}

func (x *ServeMeasurement) GetCollections() int64 {
	if x != nil {
		return x.Collections
	}
	return 0
}

func (x *ServeMeasurement) GetCollectionTime() *durationpb.Duration {
	if x != nil {
		return x.CollectionTime
	}
	return nil
}

func (x *ServeMeasurement) GetLokiStreams() int64 {
	if x != nil {
		return x.LokiStreams
	}
	return 0
}

type SystemMeasurement struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	Timestamp                *timestamppb.Timestamp    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host                     string                    `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Platform                 string                    `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Source                   string                    `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Event                    string                    `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Name                     string                    `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Boottime                 *timestamppb.Timestamp    `protobuf:"bytes,7,opt,name=boottime,proto3" json:"boottime,omitempty"`
	Uptime                   *durationpb.Duration      `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	ProcessesMaximum         int64                     `protobuf:"varint,9,opt,name=processes_maximum,json=processesMaximum,proto3" json:"processes_maximum,omitempty"`
	ProcessesPerUser         int64                     `protobuf:"varint,10,opt,name=processes_per_user,json=processesPerUser,proto3" json:"processes_per_user,omitempty"`
	OpenFilesMaximum         int64                     `protobuf:"varint,11,opt,name=open_files_maximum,json=openFilesMaximum,proto3" json:"open_files_maximum,omitempty"`
	OpenFilesPerProcess      int64                     `protobuf:"varint,12,opt,name=open_files_per_process,json=openFilesPerProcess,proto3" json:"open_files_per_process,omitempty"`
	OpenFilesCurrent         int64                     `protobuf:"varint,13,opt,name=open_files_current,json=openFilesCurrent,proto3" json:"open_files_current,omitempty"`
	LoadAverageOneMinute     float64                   `protobuf:"fixed64,14,opt,name=load_average_one_minute,json=loadAverageOneMinute,proto3" json:"load_average_one_minute,omitempty"`
	LoadAverageFiveMinute    float64                   `protobuf:"fixed64,15,opt,name=load_average_five_minute,json=loadAverageFiveMinute,proto3" json:"load_average_five_minute,omitempty"`
	LoadAverageFifteenMinute float64                   `protobuf:"fixed64,16,opt,name=load_average_fifteen_minute,json=loadAverageFifteenMinute,proto3" json:"load_average_fifteen_minute,omitempty"`
	CpuTotal                 *durationpb.Duration      `protobuf:"bytes,17,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUser                  *durationpb.Duration      `protobuf:"bytes,18,opt,name=cpu_user,json=cpuUser,proto3" json:"cpu_user,omitempty"`
	CpuSystem                *durationpb.Duration      `protobuf:"bytes,19,opt,name=cpu_system,json=cpuSystem,proto3" json:"cpu_system,omitempty"`
	CpuIdle                  *durationpb.Duration      `protobuf:"bytes,20,opt,name=cpu_idle,json=cpuIdle,proto3" json:"cpu_idle,omitempty"`
	CpuCount                 int64                     `protobuf:"varint,21,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	Cpus                     []*SystemMeasurement_Cpus `protobuf:"bytes,22,rep,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryTotal              int64                     `protobuf:"varint,23,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryFree               int64                     `protobuf:"varint,24,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	MemoryUsed               int64                     `protobuf:"varint,25,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryFreeActual         int64                     `protobuf:"varint,26,opt,name=memory_free_actual,json=memoryFreeActual,proto3" json:"memory_free_actual,omitempty"`
	MemoryUsedActual         int64                     `protobuf:"varint,27,opt,name=memory_used_actual,json=memoryUsedActual,proto3" json:"memory_used_actual,omitempty"`
	SwapTotal                int64                     `protobuf:"varint,28,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapFree                 int64                     `protobuf:"varint,29,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	SwapUsed                 int64                     `protobuf:"varint,30,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	ProcessesCount           int64                     `protobuf:"varint,31,opt,name=processes_count,json=processesCount,proto3" json:"processes_count,omitempty"`
	ProcessesActive          int64                     `protobuf:"varint,32,opt,name=processes_active,json=processesActive,proto3" json:"processes_active,omitempty"`
	ProcessesExeced          int64                     `protobuf:"varint,33,opt,name=processes_execed,json=processesExeced,proto3" json:"processes_execed,omitempty"`
	ProcessesExited          int64                     `protobuf:"varint,34,opt,name=processes_exited,json=processesExited,proto3" json:"processes_exited,omitempty"`
	ProcessesCpu             *durationpb.Duration      `protobuf:"bytes,35,opt,name=processes_cpu,json=processesCpu,proto3" json:"processes_cpu,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SystemMeasurement) Reset() {
	*x = SystemMeasurement{}
	mi := &file_gomon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMeasurement) ProtoMessage() {}

func (x *SystemMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMeasurement.ProtoReflect.Descriptor instead.
func (*SystemMeasurement) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{8}
}

func (x *SystemMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SystemMeasurement) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SystemMeasurement) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SystemMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SystemMeasurement) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SystemMeasurement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemMeasurement) GetBoottime() *timestamppb.Timestamp {
	if x != nil {
		return x.Boottime
	}
	return nil
}

func (x *SystemMeasurement) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *SystemMeasurement) GetProcessesMaximum() int64 {
	if x != nil {
		return x.ProcessesMaximum
	}
	return 0
}

func (x *SystemMeasurement) GetProcessesPerUser() int64 {
	if x != nil {
		return x.ProcessesPerUser
	}
	return 0
}

func (x *SystemMeasurement) GetOpenFilesMaximum() int64 {
	if x != nil {
		return x.OpenFilesMaximum
	}
	return 0
}

func (x *SystemMeasurement) GetOpenFilesPerProcess() int64 {
	if x != nil {
		return x.OpenFilesPerProcess
	}
	return 0
}

func (x *SystemMeasurement) GetOpenFilesCurrent() int64 {
	if x != nil {
		return x.OpenFilesCurrent
	}
	return 0
}

func (x *SystemMeasurement) GetLoadAverageOneMinute() float64 {
	if x != nil {
		return x.LoadAverageOneMinute
	}
	return 0
}

func (x *SystemMeasurement) GetLoadAverageFiveMinute() float64 {
	if x != nil {
		return x.LoadAverageFiveMinute
	}
	return 0
}

func (x *SystemMeasurement) GetLoadAverageFifteenMinute() float64 {
	if x != nil {
		return x.LoadAverageFifteenMinute
	}
	return 0
}

func (x *SystemMeasurement) GetCpuTotal() *durationpb.Duration {
	if x != nil {
		return x.CpuTotal
	}
	return nil
}

func (x *SystemMeasurement) GetCpuUser() *durationpb.Duration {
	if x != nil {
		return x.CpuUser
	}
	return nil
}

func (x *SystemMeasurement) GetCpuSystem() *durationpb.Duration {
	if x != nil {
		return x.CpuSystem
	}
	return nil
}

func (x *SystemMeasurement) GetCpuIdle() *durationpb.Duration {
	if x != nil {
		return x.CpuIdle
	}
	return nil
}

func (x *SystemMeasurement) GetCpuCount() int64 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *SystemMeasurement) GetCpus() []*SystemMeasurement_Cpus {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *SystemMeasurement) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemMeasurement) GetMemoryFree() int64 {
	if x != nil {
		return x.MemoryFree
	}
	return 0
}

func (x *SystemMeasurement) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *SystemMeasurement) GetMemoryFreeActual() int64 {
	if x != nil {
		return x.MemoryFreeActual
	}
	return 0
}

func (x *SystemMeasurement) GetMemoryUsedActual() int64 {
	if x != nil {
		return x.MemoryUsedActual
	}
	return 0
}

func (x *SystemMeasurement) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *SystemMeasurement) GetSwapFree() int64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *SystemMeasurement) GetSwapUsed() int64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *SystemMeasurement) GetProcessesCount() int64 {
	if x != nil {
		return x.ProcessesCount
	}
	return 0
}

func (x *SystemMeasurement) GetProcessesActive() int64 {
	if x != nil {
		return x.ProcessesActive
	}
	return 0
}

func (x *SystemMeasurement) GetProcessesExeced() int64 {
	if x != nil {
		return x.ProcessesExeced
	}
	return 0
}

func (x *SystemMeasurement) GetProcessesExited() int64 {
	if x != nil {
		return x.ProcessesExited
	}
	return 0
}

func (x *SystemMeasurement) GetProcessesCpu() *durationpb.Duration {
	if x != nil {
		return x.ProcessesCpu
	}
	return nil
}

type ProcessMeasurement_Connections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SelfName      string                 `protobuf:"bytes,2,opt,name=self_name,json=selfName,proto3" json:"self_name,omitempty"`
	SelfPid       int64                  `protobuf:"varint,3,opt,name=self_pid,json=selfPid,proto3" json:"self_pid,omitempty"`
	PeerName      string                 `protobuf:"bytes,4,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	PeerPid       int64                  `protobuf:"varint,5,opt,name=peer_pid,json=peerPid,proto3" json:"peer_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMeasurement_Connections) Reset() {
	*x = ProcessMeasurement_Connections{}
	mi := &file_gomon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMeasurement_Connections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMeasurement_Connections) ProtoMessage() {}

func (x *ProcessMeasurement_Connections) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMeasurement_Connections.ProtoReflect.Descriptor instead.
func (*ProcessMeasurement_Connections) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ProcessMeasurement_Connections) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessMeasurement_Connections) GetSelfName() string {
	if x != nil {
		return x.SelfName
	}
	return ""
}

func (x *ProcessMeasurement_Connections) GetSelfPid() int64 {
	if x != nil {
		return x.SelfPid
	}
	return 0
}

func (x *ProcessMeasurement_Connections) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *ProcessMeasurement_Connections) GetPeerPid() int64 {
	if x != nil {
		return x.PeerPid
	}
	return 0
}

type SystemMeasurement_Cpus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *durationpb.Duration   `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	User          *durationpb.Duration   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	System        *durationpb.Duration   `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	Idle          *durationpb.Duration   `protobuf:"bytes,4,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMeasurement_Cpus) Reset() {
	*x = SystemMeasurement_Cpus{}
	mi := &file_gomon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMeasurement_Cpus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMeasurement_Cpus) ProtoMessage() {}

func (x *SystemMeasurement_Cpus) ProtoReflect() protoreflect.Message {
	mi := &file_gomon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMeasurement_Cpus.ProtoReflect.Descriptor instead.
func (*SystemMeasurement_Cpus) Descriptor() ([]byte, []int) {
	return file_gomon_proto_rawDescGZIP(), []int{8, 0}
}

func (x *SystemMeasurement_Cpus) GetTotal() *durationpb.Duration {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *SystemMeasurement_Cpus) GetUser() *durationpb.Duration {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SystemMeasurement_Cpus) GetSystem() *durationpb.Duration {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *SystemMeasurement_Cpus) GetIdle() *durationpb.Duration {
	if x != nil {
		return x.Idle
	}
	return nil
}

var File_gomon_proto protoreflect.FileDescriptor

const file_gomon_proto_rawDesc = "" +
	"\n" +
	"\vgomon.proto\x12\x05gomon\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\x0fFileObservation\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\"\n" +
	"\rfile_event_id\x18\a \x01(\x04R\vfileEventId\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"\xfe\x02\n" +
	"\x15FilesystemMeasurement\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x14\n" +
	"\x05mount\x18\x06 \x01(\tR\x05mount\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x14\n" +
	"\x05total\x18\t \x01(\x03R\x05total\x12\x12\n" +
	"\x04used\x18\n" +
	" \x01(\x03R\x04used\x12\x12\n" +
	"\x04free\x18\v \x01(\x03R\x04free\x12\x1c\n" +
	"\tavailable\x18\f \x01(\x03R\tavailable\x12\x14\n" +
	"\x05files\x18\r \x01(\x03R\x05files\x12\x1d\n" +
	"\n" +
	"free_files\x18\x0e \x01(\x03R\tfreeFiles\"\x99\x04\n" +
	"\rIoMeasurement\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x14\n" +
	"\x05major\x18\a \x01(\tR\x05major\x12\x14\n" +
	"\x05minor\x18\b \x01(\tR\x05minor\x12\x1d\n" +
	"\n" +
	"total_size\x18\t \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"block_size\x18\n" +
	" \x01(\x03R\tblockSize\x12'\n" +
	"\x0fread_operations\x18\v \x01(\x03R\x0ereadOperations\x12\x12\n" +
	"\x04read\x18\f \x01(\x03R\x04read\x126\n" +
	"\tread_time\x18\r \x01(\v2\x19.google.protobuf.DurationR\breadTime\x12)\n" +
	"\x10write_operations\x18\x0e \x01(\x03R\x0fwriteOperations\x12\x14\n" +
	"\x05write\x18\x0f \x01(\x03R\x05write\x128\n" +
	"\n" +
	"write_time\x18\x10 \x01(\v2\x19.google.protobuf.DurationR\twriteTime\"\x81\x02\n" +
	"\x0fLogsObservation\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\a \x01(\x03R\x03pid\x12\x16\n" +
	"\x06sender\x18\b \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"\xd9\x06\n" +
	"\x12NetworkMeasurement\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\a \x01(\x03R\x05index\x12\x14\n" +
	"\x05flags\x18\b \x01(\tR\x05flags\x12\x10\n" +
	"\x03mtu\x18\t \x01(\x03R\x03mtu\x12\x10\n" +
	"\x03mac\x18\n" +
	" \x01(\tR\x03mac\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12\x18\n" +
	"\anetmask\x18\f \x01(\tR\anetmask\x12\x1c\n" +
	"\tbroadcast\x18\r \x01(\tR\tbroadcast\x12\x1e\n" +
	"\n" +
	"linklocal6\x18\x0e \x01(\tR\n" +
	"linklocal6\x12\x1a\n" +
	"\baddress6\x18\x0f \x01(\tR\baddress6\x12\x18\n" +
	"\areceive\x18\x10 \x01(\x03R\areceive\x12'\n" +
	"\x0freceive_packets\x18\x11 \x01(\x03R\x0ereceivePackets\x12%\n" +
	"\x0ereceive_errors\x18\x12 \x01(\x03R\rreceiveErrors\x12'\n" +
	"\x0freceive_dropped\x18\x13 \x01(\x03R\x0ereceiveDropped\x12+\n" +
	"\x11receive_multicast\x18\x14 \x01(\x03R\x10receiveMulticast\x12\x1a\n" +
	"\btransmit\x18\x15 \x01(\x03R\btransmit\x12)\n" +
	"\x10transmit_packets\x18\x16 \x01(\x03R\x0ftransmitPackets\x12'\n" +
	"\x0ftransmit_errors\x18\x17 \x01(\x03R\x0etransmitErrors\x12)\n" +
	"\x10transmit_dropped\x18\x18 \x01(\x03R\x0ftransmitDropped\x12/\n" +
	"\x13transmit_collisions\x18\x19 \x01(\x03R\x12transmitCollisions\x12-\n" +
	"\x12transmit_multicast\x18\x1a \x01(\x03R\x11transmitMulticast\"\xa6\x02\n" +
	"\x12ProcessObservation\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\a \x01(\x03R\x03pid\x128\n" +
	"\tstarttime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstarttime\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"\xcd\t\n" +
	"\x12ProcessMeasurement\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\a \x01(\x03R\x03pid\x128\n" +
	"\tstarttime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstarttime\x12\x12\n" +
	"\x04ppid\x18\t \x01(\x03R\x04ppid\x12\x12\n" +
	"\x04pgid\x18\n" +
	" \x01(\x03R\x04pgid\x12\x10\n" +
	"\x03tty\x18\v \x01(\tR\x03tty\x12\x10\n" +
	"\x03uid\x18\f \x01(\x03R\x03uid\x12\x10\n" +
	"\x03gid\x18\r \x01(\x03R\x03gid\x12\x1a\n" +
	"\busername\x18\x0e \x01(\tR\busername\x12\x1c\n" +
	"\tgroupname\x18\x0f \x01(\tR\tgroupname\x12\x1e\n" +
	"\n" +
	"executable\x18\x10 \x01(\tR\n" +
	"executable\x12\x12\n" +
	"\x04args\x18\x11 \x03(\tR\x04args\x12\x12\n" +
	"\x04envs\x18\x12 \x03(\tR\x04envs\x12\x10\n" +
	"\x03cwd\x18\x13 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04root\x18\x14 \x01(\tR\x04root\x12G\n" +
	"\vconnections\x18\x15 \x03(\v2%.gomon.ProcessMeasurement.ConnectionsR\vconnections\x12\x16\n" +
	"\x06status\x18\x16 \x01(\tR\x06status\x12\x12\n" +
	"\x04nice\x18\x17 \x01(\x03R\x04nice\x12\x1a\n" +
	"\bpriority\x18\x18 \x01(\x03R\bpriority\x12\x18\n" +
	"\athreads\x18\x19 \x01(\x03R\athreads\x12-\n" +
	"\x04user\x18\x1a \x01(\v2\x19.google.protobuf.DurationR\x04user\x121\n" +
	"\x06system\x18\x1b \x01(\v2\x19.google.protobuf.DurationR\x06system\x12/\n" +
	"\x05total\x18\x1c \x01(\v2\x19.google.protobuf.DurationR\x05total\x12\x12\n" +
	"\x04size\x18\x1d \x01(\x03R\x04size\x12\x1a\n" +
	"\bresident\x18\x1e \x01(\x03R\bresident\x12\x1f\n" +
	"\vpage_faults\x18\x1f \x01(\x03R\n" +
	"pageFaults\x12)\n" +
	"\x10context_switches\x18  \x01(\x03R\x0fcontextSwitches\x12\x1f\n" +
	"\vread_actual\x18! \x01(\x03R\n" +
	"readActual\x12!\n" +
	"\fwrite_actual\x18\" \x01(\x03R\vwriteActual\x12'\n" +
	"\x0fwrite_requested\x18# \x01(\x03R\x0ewriteRequested\x1a\x91\x01\n" +
	"\vConnections\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tself_name\x18\x02 \x01(\tR\bselfName\x12\x19\n" +
	"\bself_pid\x18\x03 \x01(\x03R\aselfPid\x12\x1b\n" +
	"\tpeer_name\x18\x04 \x01(\tR\bpeerName\x12\x19\n" +
	"\bpeer_pid\x18\x05 \x01(\x03R\apeerPid\"\xa4\x03\n" +
	"\x10ServeMeasurement\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1c\n" +
	"\tendpoints\x18\b \x03(\tR\tendpoints\x12#\n" +
	"\rhttp_requests\x18\t \x01(\x03R\fhttpRequests\x12 \n" +
	"\vcollections\x18\n" +
	" \x01(\x03R\vcollections\x12B\n" +
	"\x0fcollection_time\x18\v \x01(\v2\x19.google.protobuf.DurationR\x0ecollectionTime\x12!\n" +
	"\floki_streams\x18\f \x01(\x03R\vlokiStreams\"\xc2\r\n" +
	"\x11SystemMeasurement\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x126\n" +
	"\bboottime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bboottime\x121\n" +
	"\x06uptime\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12+\n" +
	"\x11processes_maximum\x18\t \x01(\x03R\x10processesMaximum\x12,\n" +
	"\x12processes_per_user\x18\n" +
	" \x01(\x03R\x10processesPerUser\x12,\n" +
	"\x12open_files_maximum\x18\v \x01(\x03R\x10openFilesMaximum\x123\n" +
	"\x16open_files_per_process\x18\f \x01(\x03R\x13openFilesPerProcess\x12,\n" +
	"\x12open_files_current\x18\r \x01(\x03R\x10openFilesCurrent\x125\n" +
	"\x17load_average_one_minute\x18\x0e \x01(\x01R\x14loadAverageOneMinute\x127\n" +
	"\x18load_average_five_minute\x18\x0f \x01(\x01R\x15loadAverageFiveMinute\x12=\n" +
	"\x1bload_average_fifteen_minute\x18\x10 \x01(\x01R\x18loadAverageFifteenMinute\x126\n" +
	"\tcpu_total\x18\x11 \x01(\v2\x19.google.protobuf.DurationR\bcpuTotal\x124\n" +
	"\bcpu_user\x18\x12 \x01(\v2\x19.google.protobuf.DurationR\acpuUser\x128\n" +
	"\n" +
	"cpu_system\x18\x13 \x01(\v2\x19.google.protobuf.DurationR\tcpuSystem\x124\n" +
	"\bcpu_idle\x18\x14 \x01(\v2\x19.google.protobuf.DurationR\acpuIdle\x12\x1b\n" +
	"\tcpu_count\x18\x15 \x01(\x03R\bcpuCount\x121\n" +
	"\x04cpus\x18\x16 \x03(\v2\x1d.gomon.SystemMeasurement.CpusR\x04cpus\x12!\n" +
	"\fmemory_total\x18\x17 \x01(\x03R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_free\x18\x18 \x01(\x03R\n" +
	"memoryFree\x12\x1f\n" +
	"\vmemory_used\x18\x19 \x01(\x03R\n" +
	"memoryUsed\x12,\n" +
	"\x12memory_free_actual\x18\x1a \x01(\x03R\x10memoryFreeActual\x12,\n" +
	"\x12memory_used_actual\x18\x1b \x01(\x03R\x10memoryUsedActual\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x1c \x01(\x03R\tswapTotal\x12\x1b\n" +
	"\tswap_free\x18\x1d \x01(\x03R\bswapFree\x12\x1b\n" +
	"\tswap_used\x18\x1e \x01(\x03R\bswapUsed\x12'\n" +
	"\x0fprocesses_count\x18\x1f \x01(\x03R\x0eprocessesCount\x12)\n" +
	"\x10processes_active\x18  \x01(\x03R\x0fprocessesActive\x12)\n" +
	"\x10processes_execed\x18! \x01(\x03R\x0fprocessesExeced\x12)\n" +
	"\x10processes_exited\x18\" \x01(\x03R\x0fprocessesExited\x12>\n" +
	"\rprocesses_cpu\x18# \x01(\v2\x19.google.protobuf.DurationR\fprocessesCpu\x1a\xc8\x01\n" +
	"\x04Cpus\x12/\n" +
	"\x05total\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05total\x12-\n" +
	"\x04user\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x04user\x121\n" +
	"\x06system\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06system\x12-\n" +
	"\x04idle\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x04idleB\x19Z\x17github.com/zosmac/gomonb\x06proto3"

var (
	file_gomon_proto_rawDescOnce sync.Once
	file_gomon_proto_rawDescData []byte
)

func file_gomon_proto_rawDescGZIP() []byte {
	file_gomon_proto_rawDescOnce.Do(func() {
		file_gomon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gomon_proto_rawDesc), len(file_gomon_proto_rawDesc)))
	})
	return file_gomon_proto_rawDescData
}

var file_gomon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gomon_proto_goTypes = []any{
	(*FileObservation)(nil),                // 0: gomon.FileObservation
	(*FilesystemMeasurement)(nil),          // 1: gomon.FilesystemMeasurement
	(*IoMeasurement)(nil),                  // 2: gomon.IoMeasurement
	(*LogsObservation)(nil),                // 3: gomon.LogsObservation
	(*NetworkMeasurement)(nil),             // 4: gomon.NetworkMeasurement
	(*ProcessObservation)(nil),             // 5: gomon.ProcessObservation
	(*ProcessMeasurement)(nil),             // 6: gomon.ProcessMeasurement
	(*ServeMeasurement)(nil),               // 7: gomon.ServeMeasurement
	(*SystemMeasurement)(nil),              // 8: gomon.SystemMeasurement
	(*ProcessMeasurement_Connections)(nil), // 9: gomon.ProcessMeasurement.Connections
	(*SystemMeasurement_Cpus)(nil),         // 10: gomon.SystemMeasurement.Cpus
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),            // 12: google.protobuf.Duration
}
var file_gomon_proto_depIdxs = []int32{
	11, // 0: gomon.FileObservation.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: gomon.FilesystemMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	11, // 2: gomon.IoMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	12, // 3: gomon.IoMeasurement.read_time:type_name -> google.protobuf.Duration
	12, // 4: gomon.IoMeasurement.write_time:type_name -> google.protobuf.Duration
	11, // 5: gomon.LogsObservation.timestamp:type_name -> google.protobuf.Timestamp
	11, // 6: gomon.NetworkMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	11, // 7: gomon.ProcessObservation.timestamp:type_name -> google.protobuf.Timestamp
	11, // 8: gomon.ProcessObservation.starttime:type_name -> google.protobuf.Timestamp
	11, // 9: gomon.ProcessMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	11, // 10: gomon.ProcessMeasurement.starttime:type_name -> google.protobuf.Timestamp
	9,  // 11: gomon.ProcessMeasurement.connections:type_name -> gomon.ProcessMeasurement.Connections
	12, // 12: gomon.ProcessMeasurement.user:type_name -> google.protobuf.Duration
	12, // 13: gomon.ProcessMeasurement.system:type_name -> google.protobuf.Duration
	12, // 14: gomon.ProcessMeasurement.total:type_name -> google.protobuf.Duration
	11, // 15: gomon.ServeMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	12, // 16: gomon.ServeMeasurement.collection_time:type_name -> google.protobuf.Duration
	11, // 17: gomon.SystemMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	11, // 18: gomon.SystemMeasurement.boottime:type_name -> google.protobuf.Timestamp
	12, // 19: gomon.SystemMeasurement.uptime:type_name -> google.protobuf.Duration
	12, // 20: gomon.SystemMeasurement.cpu_total:type_name -> google.protobuf.Duration
	12, // 21: gomon.SystemMeasurement.cpu_user:type_name -> google.protobuf.Duration
	12, // 22: gomon.SystemMeasurement.cpu_system:type_name -> google.protobuf.Duration
	12, // 23: gomon.SystemMeasurement.cpu_idle:type_name -> google.protobuf.Duration
	10, // 24: gomon.SystemMeasurement.cpus:type_name -> gomon.SystemMeasurement.Cpus
	12, // 25: gomon.SystemMeasurement.processes_cpu:type_name -> google.protobuf.Duration
	12, // 26: gomon.SystemMeasurement.Cpus.total:type_name -> google.protobuf.Duration
	12, // 27: gomon.SystemMeasurement.Cpus.user:type_name -> google.protobuf.Duration
	12, // 28: gomon.SystemMeasurement.Cpus.system:type_name -> google.protobuf.Duration
	12, // 29: gomon.SystemMeasurement.Cpus.idle:type_name -> google.protobuf.Duration
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_gomon_proto_init() }
func file_gomon_proto_init() {
	if File_gomon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gomon_proto_rawDesc), len(file_gomon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gomon_proto_goTypes,
		DependencyIndexes: file_gomon_proto_depIdxs,
		MessageInfos:      file_gomon_proto_msgTypes,
	}.Build()
	File_gomon_proto = out.File
	file_gomon_proto_goTypes = nil
	file_gomon_proto_depIdxs = nil
}
